services:

  springerp:
    build: .
    ports:
      - "8000:8080"
    network_mode: "host"

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      DatabaseName: ERPFullstackProj
      encrypt: true
      trustServerCertificate: true
      ACCEPT_EULA: true
      user: sa
      MSSQL_SA_PASSWORD: Bla12345
      ##driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    volumes:
      - mssql-data:/foo:rw
    ports:
      - "1433:1433"
    network_mode: host

##volumes:
  ##mssql-data:

